[package]
name = "sample_distributions"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "2.0.1", features = ["add", "add_assign", "mul"] }
rand = { version = "0.8.5", features = ["small_rng"], default-features = false }
